mybatis:
  mapper-locations: sqlmapper/*.xml
  type-aliases-package: com.CustomSoft.mapper
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 123123
    url: jdbc:mariadb://localhost:3306/customedu
    username: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
   multipart:
     enabled: true
     max-file-size: 20MB
     max-request-size: 20MB